parameters:
    env(ELASTICSEARCH_VERSION): '5.4'
    env(ELASTICSEARCH_CLUSTER): '["http://localhost:9200"]'
    env(TIKA_SERVER): ''
    env(EMS_PRIVATE_KEY): ''
    env(EMS_PUBLIC_KEY): ''
    env(EMS_INSTANCE_ID): 'elasticms_'
    env(EMS_NAME): '<i class="ems-icon-ball"></i> elastic<b>ms</b>'
    env(EMS_SHORTNAME): '<i class="ems-icon-ball"></i><span class="sr-only">elasticms</span>'
    env(EMS_SINGLE_TYPE_INDEX): false
    env(EMS_PAGING_SIZE): 20
    env(EMS_THEME_COLOR): 'blue'
    env(EMS_DATE_TIME_FORMAT): 'j/m/Y \a\t G:i'
    env(EMS_DATEPICKER_FORMAT): 'dd/mm/yyyy'
    env(EMS_DATEPICKER_WEEKSTART): 1
    env(EMS_DATEPICKER_DAYSOFWEEK_HIGHLIGHTED): '[0, 6]'
    env(EMS_AUDIT_INDEX): ''
    env(EMS_FROM_EMAIL_ADDRESS): 'elasticms@example.com'
    env(EMS_FROM_EMAIL_NAME): 'elasticms'
    env(EMS_ALLOW_USER_REGISTRATION): false
    env(EMS_ASSET_CONFIG_TYPE): ''
    env(EMS_ASSET_CONFIG_INDEX): ''
    env(EMS_UPLOAD_FOLDER): ''
    env(STORAGE_FOLDER): './var/assets'
    env(EMS_CIRCLES_OBJECT): ''
    env(EMS_SAVE_ASSETS_IN_DB): 'false'
    env(EMS_SFTP_SERVEUR): ''
    env(EMS_SFTP_PATH): ''
    env(EMS_SFTP_USER): ''
    env(EMS_EMS_REMOTE_SERVER): ''
    env(EMS_EMS_REMOTE_AUTHKEY): ''


ems_core:
    private_key:  '%env(string:EMS_PRIVATE_KEY)%'
    public_key:  '%env(string:EMS_PUBLIC_KEY)%'
    elasticsearch_version: '%env(string:ELASTICSEARCH_VERSION)%'
    elasticsearch_cluster: '%env(json:ELASTICSEARCH_CLUSTER)%'
    instance_id: '%env(string:EMS_INSTANCE_ID)%'
    name: '%env(string:EMS_NAME)%'
    shortname: '%env(string:EMS_SHORTNAME)%'
    paging_size: '%env(int:EMS_PAGING_SIZE)%'
    theme_color: '%env(string:EMS_THEME_COLOR)%'
    date_time_format:  '%env(string:EMS_DATE_TIME_FORMAT)%'
    datepicker_format:  '%env(string:EMS_DATEPICKER_FORMAT)%'
    datepicker_weekstart:  '%env(int:EMS_DATEPICKER_WEEKSTART)%'
    datepicker_daysofweek_highlighted: '%env(json:EMS_DATEPICKER_DAYSOFWEEK_HIGHLIGHTED)%'
    audit_index: '%env(string:EMS_AUDIT_INDEX)%'
    from_email:
        address: '%env(string:EMS_FROM_EMAIL_ADDRESS)%'
        sender_name: '%env(string:EMS_FROM_EMAIL_NAME)%'
    allow_user_registration: '%env(bool:EMS_ALLOW_USER_REGISTRATION)%'
    storage_folder: '%env(string:STORAGE_FOLDER)%'
    upload_folder: '%env(string:EMS_UPLOAD_FOLDER)%'
    circles_object: '%env(string:EMS_CIRCLES_OBJECT)%'
    asset_config_type: '%env(string:EMS_ASSET_CONFIG_TYPE)%'
    asset_config_index: '%env(string:EMS_ASSET_CONFIG_INDEX)%'
    tika_server: '%env(string:TIKA_SERVER)%'
    single_type_index: '%env(bool:EMS_SINGLE_TYPE_INDEX)%'
    save_assets_in_db: '%env(bool:EMS_SAVE_ASSETS_IN_DB)%'
    sftp_server: '%env(string:EMS_SFTP_SERVEUR)%'
    sftp_path: '%env(string:EMS_SFTP_PATH)%'
    sftp_user: '%env(string:EMS_SFTP_USER)%'
    ems_remote_host: '%env(string:EMS_EMS_REMOTE_SERVER)%'
    ems_remote_authkey: '%env(string:EMS_EMS_REMOTE_AUTHKEY)%'