parameters:
    #Deprecated parameters
    env(ELASTICSEARCH_CLUSTER): '["http://localhost:9200"]'
    env(EMS_PRIVATE_KEY): ''
    env(EMS_PUBLIC_KEY): ''
    env(S3_BUCKET): ''
    env(S3_CREDENTIALS): '[]'
    env(STORAGE_FOLDER): ''
    env(EMS_SFTP_SERVEUR): ''
    env(EMS_SFTP_PATH): ''
    env(EMS_SFTP_USER): ''
    env(EMS_EMS_REMOTE_SERVER): ''
    env(EMS_EMS_REMOTE_AUTHKEY): ''
    env(EMS_SAVE_ASSETS_IN_DB): 'false'

    #Parameters
    env(EMS_HASH_ALGO): 'sha1'
    env(EMS_ELASTICSEARCH_CONNECTION_POOL): ~
    env(EMS_ELASTICSEARCH_HOSTS): '%env(ELASTICSEARCH_CLUSTER)%'
    env(EMS_STORAGES): '[{"type":"fs","path":"%env(STORAGE_FOLDER)%"},{"type":"s3","credentials":%env(S3_CREDENTIALS)%,"bucket":"%env(S3_BUCKET)%"},{"type":"db","activate":%env(EMS_SAVE_ASSETS_IN_DB)%},{"type":"http","base-url":"%env(EMS_EMS_REMOTE_SERVER)%","auth-key":"%env(EMS_EMS_REMOTE_AUTHKEY)%"},{"type":"sftp","host":"%env(EMS_SFTP_SERVEUR)%","path":"%env(EMS_SFTP_PATH)%","username":"%env(EMS_SFTP_USER)%","public-key-file":"%env(EMS_PUBLIC_KEY)%","private-key-file":"%env(EMS_PRIVATE_KEY)%"}]'
    env(EMS_STORE_DATA_SERVICES): '[{"type":"db"}]'
    env(EMS_LOG_LEVEL): '250'
    env(EMS_BACKEND_URL): ~
    env(EMS_BACKEND_API_KEY): ~
    env(EMS_BACKEND_API_VERIFY): true
    env(EMS_BACKEND_API_TIMEOUT): '30'
    env(EMS_CORE_API_HEADERS): '{}'
    env(EMS_CORE_API_MAX_CONNECTIONS): '6'

    env(EMS_CACHE): 'file_system'
    env(EMS_CACHE_PREFIX): ~
    env(EMS_REDIS_HOST): '%env(REDIS_HOST)%'
    env(EMS_REDIS_PORT): '%env(int:REDIS_PORT)%'
    env(EMS_METRIC_ENABLED): false
    env(EMS_METRIC_HOST): ''
    env(EMS_METRIC_PORT): ~
    env(EMS_WEBALIZE_REMOVABLE_REGEX): '/([^a-zA-Z0-9_| \-.''\/])|(\.$)/'
    env(EMS_WEBALIZE_DASHABLE_REGEX): '/[\/| '']+/'
    env(EMS_EXCLUDED_CONTENT_TYPES): '[]'
    env(EMS_SLUG_SYMBOL_MAP): ~
    env(EMS_TRUSTED_IPS): '[]'

ems_common:
    hash_algo: '%env(string:EMS_HASH_ALGO)%'
    elasticsearch_connection_pool: '%env(string:EMS_ELASTICSEARCH_CONNECTION_POOL)%'
    elasticsearch_hosts: '%env(json:EMS_ELASTICSEARCH_HOSTS)%'
    storages: '%env(json:EMS_STORAGES)%'
    store_data_services: '%env(json:EMS_STORE_DATA_SERVICES)%'
    log_level: '%env(int:EMS_LOG_LEVEL)%'
    backend_url: '%env(string:EMS_BACKEND_URL)%'
    backend_api_key: '%env(string:EMS_BACKEND_API_KEY)%'
    excluded_content_types: '%env(json:EMS_EXCLUDED_CONTENT_TYPES)%'
    slug_symbol_map: '%env(json:EMS_SLUG_SYMBOL_MAP)%'
    core_api:
        headers: '%env(json:EMS_CORE_API_HEADERS)%'
        max_connections: '%env(int:EMS_CORE_API_MAX_CONNECTIONS)%'
        verify: '%env(bool:EMS_BACKEND_API_VERIFY)%'
        timeout: '%env(int:EMS_BACKEND_API_TIMEOUT)%'
    webalize:
        removable_regex: '%env(string:EMS_WEBALIZE_REMOVABLE_REGEX)%'
        dashable_regex: '%env(string:EMS_WEBALIZE_DASHABLE_REGEX)%'
    cache:
        type: '%env(EMS_CACHE)%'
        prefix: '%env(string:EMS_CACHE_PREFIX)%'
        redis:
            host: '%env(EMS_REDIS_HOST)%'
            port: '%env(int:EMS_REDIS_PORT)%'
    metric:
        enabled: '%env(bool:EMS_METRIC_ENABLED)%'
        host: '%env(string:EMS_METRIC_HOST)%'
        port: '%env(EMS_METRIC_PORT)%'
    request:
        trusted_ips: '%env(json:EMS_TRUSTED_IPS)%'

when@dev:
    ems_common:
        profiler: true
