emsco:
    resource: '@EMSCoreBundle/Resources/config/routing/all.xml'

probe:
  resource: '@EMSCommonBundle/Resources/config/routing/probe.xml'

ems_common:
    resource: 'ems_common.route.loader::load'
    type: service

emsch_routes:
    resource: 'emsch.routing.route_loader'
    type: service

forms:
  resource: '@EMSFormBundle/Resources/config/routing/form.xml'
  prefix: /emsf

forms_debug:
  resource: '@EMSFormBundle/Resources/config/routing/debug.xml'
  prefix: /emsf
